/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;

/**
 *
 * @author ryo
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

public class DeleteDialogPaket extends javax.swing.JDialog {

    private boolean deleted = false;
    
    public DeleteDialogPaket(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DeleteDialogPaket(java.awt.Frame parent, boolean modal,String idPaket, String namaPaket, String durasi, String harga) {
    super(parent, modal);
    initComponents();

    txtIdPaketDelete.setText(idPaket);
    txtNamaPaketDelete.setText(namaPaket);
    txtDurasiPaketDelete.setText(durasi);
    txtHargaPaketDelete.setText(harga);
}


    
    public boolean isDeleted() {
        return deleted; 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdPaketDelete = new javax.swing.JTextField();
        txtNamaPaketDelete = new javax.swing.JTextField();
        txtDurasiPaketDelete = new javax.swing.JTextField();
        txtHargaPaketDelete = new javax.swing.JTextField();
        btnDeletePaket = new javax.swing.JButton();
        jId = new javax.swing.JLabel();
        jGenre = new javax.swing.JLabel();
        jJudul = new javax.swing.JLabel();
        jHarga = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("KONFIRMASI HAPUS DATA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 27, -1, -1));

        txtIdPaketDelete.setEditable(false);
        getContentPane().add(txtIdPaketDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 128, 368, 39));

        txtNamaPaketDelete.setEditable(false);
        txtNamaPaketDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPaketDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamaPaketDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 185, 368, 38));

        txtDurasiPaketDelete.setEditable(false);
        txtDurasiPaketDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurasiPaketDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(txtDurasiPaketDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 241, 368, 36));

        txtHargaPaketDelete.setEditable(false);
        getContentPane().add(txtHargaPaketDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 295, 368, 37));

        btnDeletePaket.setBackground(new java.awt.Color(0, 0, 102));
        btnDeletePaket.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDeletePaket.setForeground(new java.awt.Color(204, 255, 255));
        btnDeletePaket.setText("DELETE");
        btnDeletePaket.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));
        btnDeletePaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePaketActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletePaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 110, 50));

        jId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jId.setText("ID Paket");
        getContentPane().add(jId, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 134, 117, -1));

        jGenre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jGenre.setText("Durasi");
        getContentPane().add(jGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 241, -1, -1));

        jJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jJudul.setText("Nama Paket");
        getContentPane().add(jJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 194, 130, 16));

        jHarga.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jHarga.setText("Harga");
        getContentPane().add(jHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 300, 67, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dialog/2222.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -40, 790, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaPaketDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPaketDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPaketDeleteActionPerformed

    private void btnDeletePaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePaketActionPerformed
      try {
        EntityManager em = JPAUtil.getEntityManager();
        em.getTransaction().begin();

        PaketGym p = em.find(PaketGym.class, txtIdPaketDelete.getText());
        em.remove(p); // karena sudah ON DELETE CASCADE

        em.getTransaction().commit();
        em.close();

        JOptionPane.showMessageDialog(this, "Paket dan member terkait berhasil dihapus!");

        // ✅ panggil refresh tabel dari MemberFrame
        if (getParent() instanceof MemberFrame) {
            MemberFrame parent = (MemberFrame) getParent();
            parent.refreshAllTables();
        }

        dispose();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "❌ Gagal delete: " + e.getMessage());
    }

    
    }//GEN-LAST:event_btnDeletePaketActionPerformed

    private void txtDurasiPaketDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurasiPaketDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurasiPaketDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletePaket;
    private javax.swing.JLabel jGenre;
    private javax.swing.JLabel jHarga;
    private javax.swing.JLabel jId;
    private javax.swing.JLabel jJudul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtDurasiPaketDelete;
    private javax.swing.JTextField txtHargaPaketDelete;
    private javax.swing.JTextField txtIdPaketDelete;
    private javax.swing.JTextField txtNamaPaketDelete;
    // End of variables declaration//GEN-END:variables
}
