/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;

/**
 *
 * @author ryo
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

public class DeleteDialogMember extends javax.swing.JDialog {

    private boolean deleted = false;
    
    public DeleteDialogMember(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DeleteDialogMember(java.awt.Frame parent, boolean modal,
                          String idMember, String nama, String alamat, String tipePaket) {
    super(parent, modal);
    initComponents();

    txtIdMemberDelete.setText(idMember);
    txtNamaMemberDelete.setText(nama);
    txtAlamatMemberDelete.setText(alamat);
    txtPaketMemberDelete.setText(tipePaket);
}

    
    public boolean isDeleted() {
        return deleted; 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdMemberDelete = new javax.swing.JTextField();
        txtPaketMemberDelete = new javax.swing.JTextField();
        btnDeleteMember = new javax.swing.JButton();
        jId = new javax.swing.JLabel();
        jGenre = new javax.swing.JLabel();
        jJudul = new javax.swing.JLabel();
        jHarga = new javax.swing.JLabel();
        txtNamaMemberDelete = new javax.swing.JTextField();
        txtAlamatMemberDelete = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("KONFIRMASI HAPUS DATA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 27, -1, -1));

        txtIdMemberDelete.setEditable(false);
        txtIdMemberDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMemberDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdMemberDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 350, 39));

        txtPaketMemberDelete.setEditable(false);
        txtPaketMemberDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaketMemberDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(txtPaketMemberDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 350, 38));

        btnDeleteMember.setBackground(new java.awt.Color(0, 0, 102));
        btnDeleteMember.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDeleteMember.setForeground(new java.awt.Color(204, 255, 255));
        btnDeleteMember.setText("DELETE");
        btnDeleteMember.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));
        btnDeleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMemberActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 120, 50));

        jId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jId.setText("ID Member");
        getContentPane().add(jId, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 134, 117, -1));

        jGenre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jGenre.setText("Alamat");
        getContentPane().add(jGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jJudul.setText("Nama");
        getContentPane().add(jJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 55, 16));

        jHarga.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jHarga.setText("Tipe Paket");
        getContentPane().add(jHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 110, -1));

        txtNamaMemberDelete.setEditable(false);
        txtNamaMemberDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaMemberDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamaMemberDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 350, 38));

        txtAlamatMemberDelete.setEditable(false);
        txtAlamatMemberDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatMemberDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlamatMemberDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 350, 38));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dialog/2222.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -40, 790, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaketMemberDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaketMemberDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaketMemberDeleteActionPerformed

    private void btnDeleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMemberActionPerformed
     try {
        String id = txtIdMemberDelete.getText(); // <-- JANGAN parseInt()

        EntityManager em = JPAUtil.getEntityManager();
        em.getTransaction().begin();

        MemberGym m = em.find(MemberGym.class, id); // <-- id tetap String

        em.remove(m);
        em.getTransaction().commit();
        em.close();

        JOptionPane.showMessageDialog(this, "Member berhasil dihapus!");
        dispose();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "❌ ERROR delete: " + e.getMessage());
    }
    }//GEN-LAST:event_btnDeleteMemberActionPerformed

    private void txtIdMemberDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMemberDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMemberDeleteActionPerformed

    private void txtNamaMemberDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaMemberDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMemberDeleteActionPerformed

    private void txtAlamatMemberDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatMemberDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatMemberDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteMember;
    private javax.swing.JLabel jGenre;
    private javax.swing.JLabel jHarga;
    private javax.swing.JLabel jId;
    private javax.swing.JLabel jJudul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtAlamatMemberDelete;
    private javax.swing.JTextField txtIdMemberDelete;
    private javax.swing.JTextField txtNamaMemberDelete;
    private javax.swing.JTextField txtPaketMemberDelete;
    // End of variables declaration//GEN-END:variables
}
