/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dialog;

import javax.swing.JOptionPane;

/**
 *
 * @author ryo not rio
 */
public class ForgotPasswordFrame extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPasswordFrame
     */
    
    private String correctAnswer;

    public ForgotPasswordFrame() {
        initComponents();
        cbShowPassword.addActionListener(e -> {
    if (cbShowPassword.isSelected()) {
        txtPassBaru.setEchoChar((char) 0);
        txtPassKonfirmasi.setEchoChar((char) 0);
    } else {
        txtPassBaru.setEchoChar('•');
        txtPassKonfirmasi.setEchoChar('•');
    }
});

        txtQuestion.setEditable(false);
txtAnswer.setEnabled(false);
txtPassBaru.setEnabled(false);
btnUbah.setEnabled(false);

        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlFilm1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlFilm2 = new javax.swing.JLabel();
        jId2 = new javax.swing.JLabel();
        jId = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPassBaru = new javax.swing.JPasswordField();
        btnBack = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        jId3 = new javax.swing.JLabel();
        txtQuestion = new javax.swing.JTextField();
        jId4 = new javax.swing.JLabel();
        txtAnswer = new javax.swing.JTextField();
        jId1 = new javax.swing.JLabel();
        txtPassKonfirmasi = new javax.swing.JPasswordField();
        cbShowPassword = new javax.swing.JCheckBox();

        jlFilm1.setBackground(new java.awt.Color(255, 255, 255));
        jlFilm1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jlFilm1.setForeground(new java.awt.Color(255, 204, 102));
        jlFilm1.setText("DAFTAR");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlFilm2.setBackground(new java.awt.Color(255, 255, 255));
        jlFilm2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlFilm2.setForeground(new java.awt.Color(255, 204, 102));
        jlFilm2.setText("RESET PASSWORD");
        jPanel1.add(jlFilm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jId2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jId2.setForeground(new java.awt.Color(255, 255, 255));
        jId2.setText("Your Answer :");
        jPanel1.add(jId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        jId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jId.setForeground(new java.awt.Color(255, 255, 255));
        jId.setText("Confirm Password :");
        jPanel1.add(jId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, -1, -1));
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 300, 40));

        txtPassBaru.setEnabled(false);
        txtPassBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassBaruActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 410, 40));

        btnBack.setBackground(new java.awt.Color(153, 0, 51));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 0)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 30));

        btnCari.setBackground(new java.awt.Color(0, 102, 153));
        btnCari.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setText("SEARCH");
        btnCari.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 255, 255)));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel1.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 100, 40));

        btnUbah.setBackground(new java.awt.Color(51, 153, 0));
        btnUbah.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("SAVE");
        btnUbah.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 255, 0)));
        btnUbah.setEnabled(false);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel1.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 410, 40));

        jId3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jId3.setForeground(new java.awt.Color(255, 255, 255));
        jId3.setText("Username :");
        jPanel1.add(jId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        txtQuestion.setEditable(false);
        txtQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuestionActionPerformed(evt);
            }
        });
        jPanel1.add(txtQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 410, 40));

        jId4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jId4.setForeground(new java.awt.Color(255, 255, 255));
        jId4.setText("Security Question :");
        jPanel1.add(jId4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        txtAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnswerActionPerformed(evt);
            }
        });
        txtAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAnswerKeyReleased(evt);
            }
        });
        jPanel1.add(txtAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 410, 40));

        jId1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jId1.setForeground(new java.awt.Color(255, 255, 255));
        jId1.setText("New Password :");
        jPanel1.add(jId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));

        txtPassKonfirmasi.setEnabled(false);
        txtPassKonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassKonfirmasiActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassKonfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 410, 40));

        cbShowPassword.setBackground(new java.awt.Color(51, 0, 102));
        cbShowPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        cbShowPassword.setText("Show password");
        jPanel1.add(cbShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new LoginFrame().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
     String user = txtUser.getText().trim();

    if (user.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan username terlebih dahulu!");
        return;
    }

    var em = JPAUtil.getEntityManager();
    Akun a = em.find(Akun.class, user);
    em.close();

    if (a == null) {
        JOptionPane.showMessageDialog(this, "Username tidak ditemukan!");
        return;
    }

        // Simpan jawaban aslinya
       correctAnswer = a.getSecurityAnswer();


    // Load pertanyaan
    if (a.getQuestionId() == 0) {
        txtQuestion.setText(a.getCustomQuestion());
    } else {
        txtQuestion.setText(getPertanyaanById(a.getQuestionId()));
    }

    txtAnswer.setEnabled(true);
    txtAnswer.requestFocus();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        String user = txtUser.getText().trim();
    String jawaban = txtAnswer.getText().trim();
    String pwBaru = new String(txtPassBaru.getPassword());
    String pwKonfirmasi = new String(txtPassKonfirmasi.getPassword());

    // Cek field kosong
    if (user.isEmpty() || pwBaru.isEmpty() || pwKonfirmasi.isEmpty() || jawaban.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field wajib diisi!");
        return;
    }

    // Cek konfirmasi password
    if (!pwBaru.equals(pwKonfirmasi)) {
        JOptionPane.showMessageDialog(this, 
                "Password baru dan konfirmasi password tidak sama!");
        return;
    }

    // Cek jawaban security question
    if (correctAnswer == null || !jawaban.equalsIgnoreCase(correctAnswer)) {
        JOptionPane.showMessageDialog(this, "Jawaban keamanan salah!");
        return;
    }

    var em = JPAUtil.getEntityManager();
    em.getTransaction().begin();

    Akun a = em.find(Akun.class, user);
    if (a == null) {
        JOptionPane.showMessageDialog(this, "Username tidak ditemukan!");
        em.getTransaction().rollback();
        em.close();
        return;
    }

    // Update password baru
    a.setPassword(pwBaru);

    em.getTransaction().commit();
    em.close();

    JOptionPane.showMessageDialog(this, "Password berhasil diperbarui!");
    new LoginFrame().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void txtQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuestionActionPerformed

    private void txtAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnswerActionPerformed

    private void txtPassBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassBaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassBaruActionPerformed

    private void txtAnswerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnswerKeyReleased
    if (correctAnswer != null && 
    txtAnswer.getText().trim().equalsIgnoreCase(correctAnswer)) {

    txtPassBaru.setEnabled(true);
    txtPassKonfirmasi.setEnabled(true); // 🔥 BARIS WAJIB
    btnUbah.setEnabled(true);
    txtPassBaru.requestFocus();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnswerKeyReleased

    private void txtPassKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassKonfirmasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassKonfirmasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPasswordFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnUbah;
    private javax.swing.JCheckBox cbShowPassword;
    private javax.swing.JLabel jId;
    private javax.swing.JLabel jId1;
    private javax.swing.JLabel jId2;
    private javax.swing.JLabel jId3;
    private javax.swing.JLabel jId4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlFilm1;
    private javax.swing.JLabel jlFilm2;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JPasswordField txtPassBaru;
    private javax.swing.JPasswordField txtPassKonfirmasi;
    private javax.swing.JTextField txtQuestion;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    private String getPertanyaanById(int id) {
    return switch (id) {
        case 1 -> "Siapa nama lengkap ibu kandung Anda ?";
        case 2 -> "Di kota mana Anda lahir ?";
        case 3 -> "Siapa nama sahabat masa kecil Anda ?";
        case 4 -> "Apa film bioskop favorit Anda ?";
        case 5 -> "Apa makanan favorit Anda ?";
        default -> "-";
    };
}

}
