/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;

/**
 *
 * 
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//blom
public class InsertDialogPaket extends javax.swing.JDialog {

    // simpan model dari parent
    private boolean saved = false;

    // Constructor sesuai pemanggilan di FilmBioskop: (this, true, model)
   public InsertDialogPaket(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
   
    public boolean isSaved() {
        return saved;
    }

   

 

// Ambil data film dari textfield
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGenre = new javax.swing.JLabel();
        jHarga = new javax.swing.JLabel();
        jJudul = new javax.swing.JLabel();
        jId = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIdPaketInsert = new javax.swing.JTextField();
        txtNamaPaketInsert = new javax.swing.JTextField();
        txtDurasiPaketInsert = new javax.swing.JTextField();
        txtHargaPaketInsert = new javax.swing.JTextField();
        btnSavePaketInsert = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jGenre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jGenre.setText("Durasi");
        getContentPane().add(jGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 106, -1));

        jHarga.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jHarga.setText("Harga");
        getContentPane().add(jHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jJudul.setText("Nama Paket");
        getContentPane().add(jJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 120, 16));

        jId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jId.setText("ID Paket");
        getContentPane().add(jId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("MASUKKAN NAMA PAKET");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));
        getContentPane().add(txtIdPaketInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 142, 344, 40));

        txtNamaPaketInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPaketInsertActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamaPaketInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 344, 40));

        txtDurasiPaketInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurasiPaketInsertActionPerformed(evt);
            }
        });
        getContentPane().add(txtDurasiPaketInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 344, 40));
        getContentPane().add(txtHargaPaketInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 344, 40));

        btnSavePaketInsert.setBackground(new java.awt.Color(0, 0, 102));
        btnSavePaketInsert.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSavePaketInsert.setForeground(new java.awt.Color(204, 255, 255));
        btnSavePaketInsert.setText("SAVE");
        btnSavePaketInsert.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 153)));
        btnSavePaketInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePaketInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnSavePaketInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dialog/2222.jpg"))); // NOI18N
        jLabel2.setText("     ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 760, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaPaketInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPaketInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPaketInsertActionPerformed

    private void btnSavePaketInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePaketInsertActionPerformed
      try {
        String id = txtIdPaketInsert.getText();
        String nama = txtNamaPaketInsert.getText();
        String durasi = txtDurasiPaketInsert.getText();
        double harga = Double.parseDouble(txtHargaPaketInsert.getText());

        if (id.isEmpty() || nama.isEmpty() || durasi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
            return;
        }

        EntityManager em = JPAUtil.getEntityManager();
        em.getTransaction().begin();

        PaketGym p = new PaketGym();
        p.setIdPaket(id);
        p.setNamaPaket(nama);
        p.setDurasi(durasi);
        p.setHarga(harga);

        em.persist(p);
        em.getTransaction().commit();
        em.close();

        JOptionPane.showMessageDialog(this, "Paket berhasil ditambahkan!");
        saved = true;
        dispose();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Harga harus berupa angka!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "❌ Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSavePaketInsertActionPerformed
//atas
    private void txtDurasiPaketInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurasiPaketInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurasiPaketInsertActionPerformed

   

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSavePaketInsert;
    private javax.swing.JLabel jGenre;
    private javax.swing.JLabel jHarga;
    private javax.swing.JLabel jId;
    private javax.swing.JLabel jJudul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtDurasiPaketInsert;
    private javax.swing.JTextField txtHargaPaketInsert;
    private javax.swing.JTextField txtIdPaketInsert;
    private javax.swing.JTextField txtNamaPaketInsert;
    // End of variables declaration//GEN-END:variables
}
