/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;

/**
 *
 * 
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//blom
public class InsertDialogMember extends javax.swing.JDialog {

    // simpan model dari parent
    private boolean saved = false;

    // Constructor sesuai pemanggilan di FilmBioskop: (this, true, model)
    public InsertDialogMember(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    loadComboPaket();
}


private void loadComboPaket() {
    var em = JPAUtil.getEntityManager();
    try {
        var list = em.createQuery(
            "SELECT p FROM PaketGym p ORDER BY p.namaPaket",
            PaketGym.class
        ).getResultList();

        cbPaketMemberInsert.removeAllItems();  // atau cbPaketMemberUpdate

        for (PaketGym p : list) {
            cbPaketMemberInsert.addItem(p.getNamaPaket());  
        }
    } finally {
        em.close();
    }
}


   
   
   
   
   
    public boolean isSaved() {
        return saved;
    }

   

 

// Ambil data film dari textfield
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGenre = new javax.swing.JLabel();
        jHarga = new javax.swing.JLabel();
        jJudul = new javax.swing.JLabel();
        jId = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIdMemberInsert = new javax.swing.JTextField();
        txtNamaMemberInsert = new javax.swing.JTextField();
        txtAlamatMemberInsert = new javax.swing.JTextField();
        btnSaveMemberInsert = new javax.swing.JButton();
        cbPaketMemberInsert = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jGenre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jGenre.setText("Alamat");
        getContentPane().add(jGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 106, -1));

        jHarga.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jHarga.setText("Tipe Paket");
        getContentPane().add(jHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jJudul.setText("Nama");
        getContentPane().add(jJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 55, 16));

        jId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jId.setText("ID Member");
        getContentPane().add(jId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("MASUKKAN DATA MEMBER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));
        getContentPane().add(txtIdMemberInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 142, 350, 40));

        txtNamaMemberInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaMemberInsertActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamaMemberInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 350, 40));

        txtAlamatMemberInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatMemberInsertActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlamatMemberInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 350, 40));

        btnSaveMemberInsert.setBackground(new java.awt.Color(0, 0, 102));
        btnSaveMemberInsert.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSaveMemberInsert.setForeground(new java.awt.Color(204, 255, 255));
        btnSaveMemberInsert.setText("SAVE");
        btnSaveMemberInsert.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 204)));
        btnSaveMemberInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveMemberInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveMemberInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 100, 40));

        cbPaketMemberInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaketMemberInsertActionPerformed(evt);
            }
        });
        getContentPane().add(cbPaketMemberInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 350, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dialog/2222.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -50, 790, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaMemberInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaMemberInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMemberInsertActionPerformed

    private void btnSaveMemberInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMemberInsertActionPerformed
     try {
        var em = JPAUtil.getEntityManager();
        em.getTransaction().begin();

        String namaPaket = cbPaketMemberInsert.getSelectedItem().toString();

        PaketGym paket = em.createQuery(
                "SELECT p FROM PaketGym p WHERE p.namaPaket = :n",
                PaketGym.class
        ).setParameter("n", namaPaket).getSingleResult();

        MemberGym member = new MemberGym();
        member.setIdMember(txtIdMemberInsert.getText());
        member.setNama(txtNamaMemberInsert.getText());
        member.setAlamat(txtAlamatMemberInsert.getText());
        member.setPaket(paket);

        em.persist(member);
        em.getTransaction().commit();
        em.close();

        saved = true;  // ✅ WAJIB! supaya MemberFrame tau bahwa insert sukses

        JOptionPane.showMessageDialog(this, "Member berhasil ditambahkan!");
        dispose();     // tutup dialog

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "❌ Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSaveMemberInsertActionPerformed
//atas
    private void txtAlamatMemberInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatMemberInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatMemberInsertActionPerformed

    private void cbPaketMemberInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaketMemberInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPaketMemberInsertActionPerformed

   

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveMemberInsert;
    private javax.swing.JComboBox<String> cbPaketMemberInsert;
    private javax.swing.JLabel jGenre;
    private javax.swing.JLabel jHarga;
    private javax.swing.JLabel jId;
    private javax.swing.JLabel jJudul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtAlamatMemberInsert;
    private javax.swing.JTextField txtIdMemberInsert;
    private javax.swing.JTextField txtNamaMemberInsert;
    // End of variables declaration//GEN-END:variables

   
}
