/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dialog;

/**
 *
 * @author ryo not rio
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlFilm1 = new javax.swing.JLabel();
        jId = new javax.swing.JLabel();
        lblBuat = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jId2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblLupa1 = new javax.swing.JLabel();
        lblLupa2 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        cbShowPassword = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlFilm1.setBackground(new java.awt.Color(255, 255, 255));
        jlFilm1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlFilm1.setForeground(new java.awt.Color(255, 204, 102));
        jlFilm1.setText("LOGIN PAGE");
        jPanel1.add(jlFilm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jId.setForeground(new java.awt.Color(255, 255, 255));
        jId.setText("Password :");
        jPanel1.add(jId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        lblBuat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBuat.setForeground(new java.awt.Color(255, 255, 255));
        lblBuat.setText("Sign up");
        lblBuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuatMouseClicked(evt);
            }
        });
        jPanel1.add(lblBuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 390, 40));

        jId2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jId2.setForeground(new java.awt.Color(255, 255, 255));
        jId2.setText("Username :");
        jPanel1.add(jId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        btnLogin.setBackground(new java.awt.Color(0, 153, 0));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOG IN");
        btnLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 255, 0)));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 390, 40));

        lblLupa1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLupa1.setForeground(new java.awt.Color(255, 255, 255));
        lblLupa1.setText("Forgot password?");
        lblLupa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLupa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLupa1MouseClicked(evt);
            }
        });
        jPanel1.add(lblLupa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));

        lblLupa2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLupa2.setForeground(new java.awt.Color(255, 255, 255));
        lblLupa2.setText("Don't have an account ?");
        jPanel1.add(lblLupa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 390, 40));

        cbShowPassword.setBackground(new java.awt.Color(51, 0, 102));
        cbShowPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        cbShowPassword.setText("Show password");
        cbShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(cbShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLupa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLupa1MouseClicked
    new ForgotPasswordFrame().setVisible(true);
this.dispose();

                // TODO add your handling code here:
    }//GEN-LAST:event_lblLupa1MouseClicked

    private void lblBuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuatMouseClicked
        new RegisterFrame().setVisible(true);
this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_lblBuatMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
     String user = txtUser.getText().trim();
    String pw   = new String(txtPass.getPassword());  // <- JPasswordField

    if (user.isEmpty() || pw.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Isi username dan password dulu.");
        return;
    }

    var em = JPAUtil.getEntityManager();
    em.getTransaction().begin();

    Akun akun = em.find(Akun.class, user);

    if (akun == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Username tidak ditemukan.");
        txtUser.requestFocus();
    } else if (!akun.getPassword().equals(pw)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Password salah.");
        txtPass.setText("");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Anda berhasil login !");

        new MemberFrame().setVisible(true); // masuk ke aplikasi kamu
        this.dispose();
    }

    em.getTransaction().commit();
    em.close();      // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void cbShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPasswordActionPerformed
     if (cbShowPassword.isSelected()) {
        txtPass.setEchoChar((char) 0);  // password kelihatan
    } else {
        txtPass.setEchoChar('•'); // atau default: (char)8226
    }        // TODO add your handling code here:
    }//GEN-LAST:event_cbShowPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox cbShowPassword;
    private javax.swing.JLabel jId;
    private javax.swing.JLabel jId2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlFilm1;
    private javax.swing.JLabel lblBuat;
    private javax.swing.JLabel lblLupa1;
    private javax.swing.JLabel lblLupa2;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
