
package Dialog;
//blomm

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.persistence.EntityManager;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import Dialog.MemberGym;
import Dialog.PaketGym;
import Dialog.JPAUtil;
import java.io.InputStream;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;
 
public class MemberFrame extends javax.swing.JFrame {

    private DefaultTableModel model;
    
 public MemberFrame() {

    // === Buat panel custom DI SINI, bukan di initComponents ===
    panelMember = new javax.swing.JPanel();
    panelMember.setBackground(new java.awt.Color(51, 0, 102)); // warna ungu tema kamu

    initComponents();

    // setelah komponen GUI jadi, baru load data
    loadTablePaket();
    loadTableMember();
}
 public void refreshAllTables() {
    loadDataPaket();
    loadDataMember();
}


 
    private void loadTablePaket() {
    EntityManager em = JPAUtil.getEntityManager();

    try {
        List<PaketGym> list = em.createQuery(
            "SELECT p FROM PaketGym p", PaketGym.class                    
        ).getResultList();

        DefaultTableModel model = (DefaultTableModel) tabelPaket.getModel();
        model.setRowCount(0);

        for (PaketGym p : list) {
            model.addRow(new Object[]{
                p.getIdPaket(),
                p.getNamaPaket(),
                p.getDurasi(),
                p.getHarga()
            });
        }

    } finally {
        em.close();
    }
}
    
    private void loadTableMember() {
    EntityManager em = JPAUtil.getEntityManager();

    try {
        List<MemberGym> members = em.createQuery(
            "SELECT m FROM MemberGym m", MemberGym.class
        ).getResultList();

        DefaultTableModel model = (DefaultTableModel) tblMember.getModel();
        model.setRowCount(0);

        for (MemberGym m : members) {
            model.addRow(new Object[]{
                m.getIdMember(),
                m.getNama(),
                m.getAlamat(),
                (m.getPaket() != null ? m.getPaket().getNamaPaket() : "-")
            });
        }

    } finally {
        em.close();
    }
}

    
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        panelPaket = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelPaket = new javax.swing.JTable();
        jlFilm1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnInsertPaket = new javax.swing.JButton();
        btnUpdatePaket = new javax.swing.JButton();
        btnDeletePaket = new javax.swing.JButton();
        btnUploadPaket = new javax.swing.JButton();
        btnPrintPaket = new javax.swing.JButton();
        btnDownloadPaket = new javax.swing.JButton();
        btnClose2 = new javax.swing.JButton();
        panelMember = new javax.swing.JPanel();
        tabelMember = new javax.swing.JScrollPane();
        tblMember = new javax.swing.JTable();
        jlFilm = new javax.swing.JLabel();
        btnInsertMember = new javax.swing.JButton();
        btnUpdateMember = new javax.swing.JButton();
        btnDeleteMember = new javax.swing.JButton();
        btnUploadMember = new javax.swing.JButton();
        btnPrintMember = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnDownloadMember = new javax.swing.JButton();
        btnLogout2 = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jLabel1.setText("jLabel1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPaket.setBackground(new java.awt.Color(51, 0, 102));
        panelPaket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setBackground(new java.awt.Color(0, 0, 153));
        jScrollPane4.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane4.setViewportBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jScrollPane4.setAlignmentX(1.0F);
        jScrollPane4.setAlignmentY(1.0F);
        jScrollPane4.setAutoscrolls(true);
        jScrollPane4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        tabelPaket.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        tabelPaket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Paket", "Nama Paket", "Durasi", "Harga"
            }
        ));
        jScrollPane4.setViewportView(tabelPaket);

        panelPaket.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 630, 300));

        jlFilm1.setBackground(new java.awt.Color(255, 255, 255));
        jlFilm1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jlFilm1.setForeground(new java.awt.Color(255, 204, 102));
        jlFilm1.setText("PAKET GYM");
        panelPaket.add(jlFilm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(204, 255, 255));
        btnLogout.setText("LOG OUT");
        btnLogout.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 0)));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        panelPaket.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 30));

        btnInsertPaket.setBackground(new java.awt.Color(0, 153, 51));
        btnInsertPaket.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnInsertPaket.setForeground(new java.awt.Color(204, 255, 255));
        btnInsertPaket.setText("INSERT");
        btnInsertPaket.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 255, 0)));
        btnInsertPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertPaketActionPerformed(evt);
            }
        });
        panelPaket.add(btnInsertPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 110, 40));

        btnUpdatePaket.setBackground(new java.awt.Color(0, 102, 153));
        btnUpdatePaket.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdatePaket.setForeground(new java.awt.Color(204, 255, 255));
        btnUpdatePaket.setText("UPDATE");
        btnUpdatePaket.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 204, 204)));
        btnUpdatePaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePaketActionPerformed(evt);
            }
        });
        panelPaket.add(btnUpdatePaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 110, 40));

        btnDeletePaket.setBackground(new java.awt.Color(204, 0, 0));
        btnDeletePaket.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDeletePaket.setForeground(new java.awt.Color(204, 255, 255));
        btnDeletePaket.setText("DELETE");
        btnDeletePaket.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 51, 102)));
        btnDeletePaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePaketActionPerformed(evt);
            }
        });
        panelPaket.add(btnDeletePaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 110, 40));

        btnUploadPaket.setBackground(new java.awt.Color(153, 102, 0));
        btnUploadPaket.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUploadPaket.setForeground(new java.awt.Color(204, 255, 255));
        btnUploadPaket.setText("UPLOAD");
        btnUploadPaket.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 204, 0)));
        btnUploadPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadPaketActionPerformed(evt);
            }
        });
        panelPaket.add(btnUploadPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 110, 40));

        btnPrintPaket.setBackground(new java.awt.Color(102, 0, 102));
        btnPrintPaket.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrintPaket.setForeground(new java.awt.Color(204, 255, 255));
        btnPrintPaket.setText("PRINT");
        btnPrintPaket.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 204)));
        btnPrintPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintPaketActionPerformed(evt);
            }
        });
        panelPaket.add(btnPrintPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 280, 40));

        btnDownloadPaket.setBackground(new java.awt.Color(0, 0, 204));
        btnDownloadPaket.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDownloadPaket.setForeground(new java.awt.Color(204, 255, 255));
        btnDownloadPaket.setText("DOWLOAD CSV");
        btnDownloadPaket.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));
        btnDownloadPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadPaketActionPerformed(evt);
            }
        });
        panelPaket.add(btnDownloadPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 280, 40));

        btnClose2.setBackground(new java.awt.Color(255, 0, 0));
        btnClose2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnClose2.setForeground(new java.awt.Color(204, 255, 255));
        btnClose2.setText("X");
        btnClose2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 0)));
        btnClose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose2ActionPerformed(evt);
            }
        });
        panelPaket.add(btnClose2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 60, 40));

        jTabbedPane2.addTab("Paket GYM", panelPaket);

        panelMember.setBackground(new java.awt.Color(51, 0, 102));
        panelMember.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                panelMemberComponentAdded(evt);
            }
        });
        panelMember.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelMember.setBackground(new java.awt.Color(0, 0, 153));
        tabelMember.setBorder(new javax.swing.border.MatteBorder(null));
        tabelMember.setViewportBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        tabelMember.setAlignmentX(1.0F);
        tabelMember.setAlignmentY(1.0F);
        tabelMember.setAutoscrolls(true);
        tabelMember.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        tblMember.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        tblMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Member", "Nama", "Alamat", "Tipe Paket"
            }
        ));
        tabelMember.setViewportView(tblMember);

        panelMember.add(tabelMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 630, 300));

        jlFilm.setBackground(new java.awt.Color(255, 255, 255));
        jlFilm.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jlFilm.setForeground(new java.awt.Color(255, 204, 102));
        jlFilm.setText("DATA MEMBER ");
        panelMember.add(jlFilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        btnInsertMember.setBackground(new java.awt.Color(0, 153, 51));
        btnInsertMember.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnInsertMember.setForeground(new java.awt.Color(204, 255, 255));
        btnInsertMember.setText("INSERT");
        btnInsertMember.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 255, 0)));
        btnInsertMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertMemberActionPerformed(evt);
            }
        });
        panelMember.add(btnInsertMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 110, 40));

        btnUpdateMember.setBackground(new java.awt.Color(0, 102, 153));
        btnUpdateMember.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdateMember.setForeground(new java.awt.Color(204, 255, 255));
        btnUpdateMember.setText("UPDATE");
        btnUpdateMember.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 204, 204)));
        btnUpdateMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMemberActionPerformed(evt);
            }
        });
        panelMember.add(btnUpdateMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 110, 40));

        btnDeleteMember.setBackground(new java.awt.Color(204, 0, 0));
        btnDeleteMember.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDeleteMember.setForeground(new java.awt.Color(204, 255, 255));
        btnDeleteMember.setText("DELETE");
        btnDeleteMember.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 51, 102)));
        btnDeleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMemberActionPerformed(evt);
            }
        });
        panelMember.add(btnDeleteMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 110, 40));

        btnUploadMember.setBackground(new java.awt.Color(153, 102, 0));
        btnUploadMember.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUploadMember.setForeground(new java.awt.Color(204, 255, 255));
        btnUploadMember.setText("UPLOAD");
        btnUploadMember.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 204, 0)));
        btnUploadMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadMemberActionPerformed(evt);
            }
        });
        panelMember.add(btnUploadMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 110, 40));

        btnPrintMember.setBackground(new java.awt.Color(102, 0, 102));
        btnPrintMember.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrintMember.setForeground(new java.awt.Color(204, 255, 255));
        btnPrintMember.setText("PRINT");
        btnPrintMember.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 204)));
        btnPrintMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintMemberActionPerformed(evt);
            }
        });
        panelMember.add(btnPrintMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 280, 40));

        btnClose.setBackground(new java.awt.Color(255, 0, 0));
        btnClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnClose.setForeground(new java.awt.Color(204, 255, 255));
        btnClose.setText("X");
        btnClose.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 0)));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        panelMember.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 60, 40));

        btnDownloadMember.setBackground(new java.awt.Color(0, 0, 204));
        btnDownloadMember.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDownloadMember.setForeground(new java.awt.Color(204, 255, 255));
        btnDownloadMember.setText("DOWLOAD CSV");
        btnDownloadMember.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));
        btnDownloadMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadMemberActionPerformed(evt);
            }
        });
        panelMember.add(btnDownloadMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 280, 40));

        btnLogout2.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogout2.setForeground(new java.awt.Color(204, 255, 255));
        btnLogout2.setText("LOG OUT");
        btnLogout2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 0)));
        btnLogout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout2ActionPerformed(evt);
            }
        });
        panelMember.add(btnLogout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 30));

        jTabbedPane2.addTab("Member GYM", panelMember);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked

    }//GEN-LAST:event_TabelMouseClicked

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
            this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnDeleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMemberActionPerformed
int row = tblMember.getSelectedRow();
if (row == -1) return;

// ambil nilai dari JTable
String id = tblMember.getValueAt(row, 0).toString();
String nama = tblMember.getValueAt(row, 1).toString();
String alamat = tblMember.getValueAt(row, 2).toString();
String paket = tblMember.getValueAt(row, 3).toString();

// panggil dialog delete member
DeleteDialogMember dlg = new DeleteDialogMember(this, true, id, nama, alamat, paket);
dlg.setVisible(true);

loadTableMember();  // refresh tabel setelah delete


    }//GEN-LAST:event_btnDeleteMemberActionPerformed

    private void btnUpdateMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMemberActionPerformed
    int row = tblMember.getSelectedRow();
    if (row == -1) return;

    String id = tblMember.getValueAt(row, 0).toString();

    UpdateDialogMember dlg = new UpdateDialogMember(this, true, id);
    dlg.setVisible(true);
    loadTableMember();
    }//GEN-LAST:event_btnUpdateMemberActionPerformed

    private void btnInsertMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertMemberActionPerformed
    InsertDialogMember dlg = new InsertDialogMember(this, true);
dlg.setVisible(true);
if (dlg.isSaved()) {
    loadTableMember();
}
 



    }//GEN-LAST:event_btnInsertMemberActionPerformed

    private void btnPrintMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintMemberActionPerformed
     try {
        Connection conn = JPAUtil.getConnection();  // <- pake JDBC langsung

        JasperPrint jp = JasperFillManager.fillReport(
                getClass().getResourceAsStream("/Dialog/report_member.jasper"),
                null,
                conn
        );

        JasperViewer.viewReport(jp, false);
        conn.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "❌ Error cetak report Member:\n" + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnPrintMemberActionPerformed

    private void btnUploadMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadMemberActionPerformed
         JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Pilih file CSV Member Gym");

    int result = chooser.showOpenDialog(this);
    if (result != JFileChooser.APPROVE_OPTION) return;

    File fileCSV = chooser.getSelectedFile();

    try (BufferedReader br = new BufferedReader(new FileReader(fileCSV))) {

        Connection conn = JPAUtil.getConnection();
        conn.setAutoCommit(false);

        String line;
        int totalInsert = 0;
        boolean firstLine = true;

        while ((line = br.readLine()) != null) {

            line = line.trim();
            if (line.isEmpty()) continue; // skip baris kosong

            String[] data = line.split("[,;]"); // bisa koma atau titik koma

            if (firstLine) {  // skip header
                firstLine = false;
                if (data[0].toLowerCase().contains("id")) continue;
            }

            if (data.length < 4) {
                System.out.println("❌ Format salah: " + line);
                continue;
            }

            // Remove BOM data[0] biar nggak ada simbol aneh
            String id_member = data[0].replace("\uFEFF", "").trim();
            String nama = data[1].trim();
            String id_paket = data[2].trim();
            String alamat = data[3].trim();

            PreparedStatement pst = conn.prepareStatement(
                    "INSERT INTO member_gym (id_member, nama, id_paket, alamat) VALUES (?, ?, ?, ?)"
            );

            pst.setString(1, id_member);
            pst.setString(2, nama);
            pst.setString(3, id_paket);
            pst.setString(4, alamat);

            pst.executeUpdate();
            totalInsert++;
        }

        conn.commit();
        conn.close();

        JOptionPane.showMessageDialog(this,
                totalInsert + " data member berhasil diimport!",
                "SUCCESS",
                JOptionPane.INFORMATION_MESSAGE);

        loadDataMember(); // ⚡ refresh otomatis ke tabel

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Gagal import CSV!\n" + e.getMessage(),
                "ERROR",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnUploadMemberActionPerformed

    private void panelMemberComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_panelMemberComponentAdded

    }//GEN-LAST:event_panelMemberComponentAdded

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
       int confirm = JOptionPane.showConfirmDialog(
        this, 
        "Yakin ingin logout?", 
        "Konfirmasi Logout", 
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        new LoginFrame().setVisible(true);
        this.dispose(); 
    } // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnInsertPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertPaketActionPerformed
    InsertDialogPaket dlg = new InsertDialogPaket(this, true);
    dlg.setVisible(true);
    loadTablePaket();        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertPaketActionPerformed

    private void btnUpdatePaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePaketActionPerformed
    int row = tabelPaket.getSelectedRow();
    if (row == -1) return;

    String id = tabelPaket.getValueAt(row, 0).toString();
    String nama = tabelPaket.getValueAt(row, 1).toString();
    String durasi = tabelPaket.getValueAt(row, 2).toString();
    String harga = tabelPaket.getValueAt(row, 3).toString();

    UpdateDialogPaket dlg = new UpdateDialogPaket(this, true, id, nama, durasi, harga);
    dlg.setVisible(true);
    loadTablePaket();   // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdatePaketActionPerformed

    private void btnDeletePaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePaketActionPerformed
    int row = tabelPaket.getSelectedRow();
    if (row == -1) return;

    String id = tabelPaket.getValueAt(row, 0).toString();
    String nama = tabelPaket.getValueAt(row, 1).toString();   
    String durasi = tabelPaket.getValueAt(row, 2).toString();
    String harga = tabelPaket.getValueAt(row, 3).toString();

DeleteDialogPaket dlg = new DeleteDialogPaket(this, true, id,
        nama, durasi, harga);
dlg.setVisible(true);
loadTablePaket();   // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletePaketActionPerformed

    private void btnUploadPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPaketActionPerformed
      JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Pilih file CSV Paket Gym");

    int result = chooser.showOpenDialog(this);
    if (result != JFileChooser.APPROVE_OPTION) {
        return;
    }

    File fileCSV = chooser.getSelectedFile();

    try (BufferedReader br = new BufferedReader(new FileReader(fileCSV))) {

        Connection conn = JPAUtil.getConnection();
        conn.setAutoCommit(false); // biar lebih cepat

        String line;
        int totalInsert = 0;
        boolean firstLine = true;

        while ((line = br.readLine()) != null) {

            line = line.trim();
            if (line.isEmpty()) continue; // skip baris kosong

            String[] data = line.split("[,;]"); // bisa koma / titik koma

            if (firstLine) {  // skip header kalau ada
                firstLine = false;
                if (data[0].toLowerCase().contains("id")) continue;
            }

            if (data.length < 4) {
                System.out.println("Format salah: " + line);
                continue;
            }

            String id_paket = data[0].replace("\uFEFF", "").trim();
            String nama_paket = data[1].replace("\uFEFF", "").trim();
            String durasi = data[2].replace("\uFEFF", "").trim();
            String harga = data[3].replace("\uFEFF", "").trim();

            PreparedStatement pst = conn.prepareStatement(
                "INSERT INTO paket_gym (id_paket, nama_paket, durasi, harga) VALUES (?, ?, ?, ?)"
            );

            pst.setString(1, id_paket);
            pst.setString(2, nama_paket);
            pst.setString(3, durasi);
            pst.setBigDecimal(4, new java.math.BigDecimal(harga));

            pst.executeUpdate();
            totalInsert++;
        }

        conn.commit();
        conn.close();

        JOptionPane.showMessageDialog(this,
                totalInsert + " data paket berhasil diimport!",
                "SUCCESS",
                JOptionPane.INFORMATION_MESSAGE);

        loadDataPaket(); // 🔥 refresh tabel otomatis

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "❌ Gagal import CSV!\n" + e.getMessage(),
                "ERROR",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnUploadPaketActionPerformed

    private void btnPrintPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintPaketActionPerformed
         try {
        Connection conn = JPAUtil.getConnection();

        JasperPrint print = JasperFillManager.fillReport(
                getClass().getResourceAsStream("/Dialog/report_paket.jasper"),
                null,
                conn
        );

        JasperViewer viewer = new JasperViewer(print, false);
        viewer.setVisible(true);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error cetak report: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnPrintPaketActionPerformed

    private void btnDownloadPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadPaketActionPerformed
    try {
        var em = JPAUtil.getEntityManager();
        java.util.List<PaketGym> list = em.createQuery("SELECT p FROM PaketGym p", PaketGym.class).getResultList();
        em.close();

        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setDialogTitle("Save Paket CSV");
        chooser.setSelectedFile(new java.io.File("paket_backup.csv"));
        
        int userSelection = chooser.showSaveDialog(this);
        if (userSelection != javax.swing.JFileChooser.APPROVE_OPTION) return;

        java.io.PrintWriter pw = new java.io.PrintWriter(chooser.getSelectedFile());

        pw.println("id_paket,nama_paket,durasi,harga");

        for (PaketGym p : list) {
            pw.println(p.getIdPaket() + "," +
                       p.getNamaPaket() + "," +
                       p.getDurasi() + "," +
                       p.getHarga());
        }

        pw.close();
        JOptionPane.showMessageDialog(this, "Data Paket berhasil didownload!");

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal download CSV: " + e.getMessage());
    }       // TODO add your handling code here:
    }//GEN-LAST:event_btnDownloadPaketActionPerformed

    private void btnDownloadMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadMemberActionPerformed
    try {
        var em = JPAUtil.getEntityManager();
List<MemberGym> list = em.createQuery(
    "SELECT m FROM MemberGym m ORDER BY m.idMember",
    MemberGym.class
).getResultList();
em.close();


        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setDialogTitle("Save Member CSV");
        chooser.setSelectedFile(new java.io.File("member_backup.csv"));
        
        int userSelection = chooser.showSaveDialog(this);
        if (userSelection != javax.swing.JFileChooser.APPROVE_OPTION) return;

        java.io.PrintWriter pw = new java.io.PrintWriter(chooser.getSelectedFile());

        pw.println("id_member,nama,id_paket,alamat");


        for (MemberGym m : list) {
           pw.println(m.getIdMember() + "," +
           m.getNama() + "," +
           m.getPaket().getIdPaket() + "," +
           m.getAlamat());

        }

        pw.close();
        JOptionPane.showMessageDialog(this, "Data Member berhasil didownload!");

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal download CSV: " + e.getMessage());
    }   // TODO add your handling code here:
    }//GEN-LAST:event_btnDownloadMemberActionPerformed

    private void btnClose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose2ActionPerformed
      this.dispose();
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnClose2ActionPerformed

    private void btnLogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout2ActionPerformed
     int confirm = JOptionPane.showConfirmDialog(
        this, 
        "Yakin ingin logout?", 
        "Konfirmasi Logout", 
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        new LoginFrame().setVisible(true);
        this.dispose(); 
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogout2ActionPerformed
//blom
    /**
     * @param args the command line arguments
     */
  public static void main(String[] args) {
    new LoginFrame().setVisible(true);  // <- ini supaya yang muncul pertama form login
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnClose2;
    private javax.swing.JButton btnDeleteMember;
    private javax.swing.JButton btnDeletePaket;
    private javax.swing.JButton btnDownloadMember;
    private javax.swing.JButton btnDownloadPaket;
    private javax.swing.JButton btnInsertMember;
    private javax.swing.JButton btnInsertPaket;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogout2;
    private javax.swing.JButton btnPrintMember;
    private javax.swing.JButton btnPrintPaket;
    private javax.swing.JButton btnUpdateMember;
    private javax.swing.JButton btnUpdatePaket;
    private javax.swing.JButton btnUploadMember;
    private javax.swing.JButton btnUploadPaket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jlFilm;
    private javax.swing.JLabel jlFilm1;
    private javax.swing.JPanel panelMember;
    private javax.swing.JPanel panelPaket;
    private javax.swing.JScrollPane tabelMember;
    private javax.swing.JTable tabelPaket;
    private javax.swing.JTable tblMember;
    // End of variables declaration//GEN-END:variables

   private void loadDataPaket() {
    try {
        Connection conn = JPAUtil.getConnection();
        String sql = "SELECT id_paket, nama_paket, durasi, harga FROM paket_gym";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Paket");
        model.addColumn("Nama Paket");
        model.addColumn("Durasi");
        model.addColumn("Harga");

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_paket"),
                rs.getString("nama_paket"),
                rs.getString("durasi"),
                rs.getBigDecimal("harga")
            });
        }

        tabelPaket.setModel(model); // <--- ini tabel yang ada di form kamu
        conn.close();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Gagal load data paket!\n" + e.getMessage(),
                "ERROR",
                JOptionPane.ERROR_MESSAGE);
    }
}

    private void loadDataMember() {
 try {
        Connection conn = JPAUtil.getConnection();
        String sql = "SELECT m.id_member, m.nama, p.nama_paket AS tipe_paket, m.alamat " +
                     "FROM member_gym m " +
                     "JOIN paket_gym p ON m.id_paket = p.id_paket " +
                     "ORDER BY m.id_member";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Member");
        model.addColumn("Nama");
        model.addColumn("Tipe Paket");
        model.addColumn("Alamat");

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_member"),
                rs.getString("nama"),
                rs.getString("tipe_paket"),
                rs.getString("alamat")
            });
        }

        tblMember.setModel(model);
        conn.close();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Gagal load data member!\n" + e.getMessage(),
                "ERROR",
                JOptionPane.ERROR_MESSAGE);
    }
}



   

}

//bener