/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dialog;

import javax.swing.JOptionPane;

/**
 *
 * @author ryo not rio
 */
public class RegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFrame
     */
    public RegisterFrame() {
        initComponents();
        // 👁 Fitur Show / Hide Password
        cbShowPassword.addActionListener(e -> {
        if (cbShowPassword.isSelected()) {
        txtPass.setEchoChar((char) 0);
        txtConfirmPassword.setEchoChar((char) 0);
        } else {
        txtPass.setEchoChar('•');
        txtConfirmPassword.setEchoChar('•');
    }
});

        
    cbQuestion.removeAllItems();
    cbQuestion.addItem("Siapa nama lengkap ibu kandung Anda ?");
    cbQuestion.addItem("Di kota mana Anda lahir ?");
    cbQuestion.addItem("Siapa nama sahabat masa kecil Anda ?");
    cbQuestion.addItem("Apa film bioskop favorit Anda ?");
    cbQuestion.addItem("Apa makanan favorit Anda ?");

    // Tidak pilih apa-apa di awal (biar user jelas harus pilih salah satu)
    cbQuestion.setSelectedIndex(-1);
    
    // Default: custom question disabled
txtCustomQuestion.setEnabled(true);

// Listener untuk dropdown
cbQuestion.addActionListener(e -> {
    if (cbQuestion.getSelectedIndex() != -1) {
        txtCustomQuestion.setText("");
        txtCustomQuestion.setEnabled(false);
    } else {
        txtCustomQuestion.setEnabled(true);
    }
});

// Listener untuk custom question input
txtCustomQuestion.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
    private void update() {
        if (!txtCustomQuestion.getText().trim().isEmpty()) {
            cbQuestion.setSelectedIndex(-1);
            txtCustomQuestion.setEnabled(true);
        }
    }
    public void insertUpdate(javax.swing.event.DocumentEvent e) { update(); }
    public void removeUpdate(javax.swing.event.DocumentEvent e) { update(); }
    public void changedUpdate(javax.swing.event.DocumentEvent e) { update(); }
});

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jlFilm1 = new javax.swing.JLabel();
        jId = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnBuat = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jId3 = new javax.swing.JLabel();
        cbQuestion = new javax.swing.JComboBox<>();
        jId6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jId1 = new javax.swing.JLabel();
        jId7 = new javax.swing.JLabel();
        jId8 = new javax.swing.JLabel();
        jId10 = new javax.swing.JLabel();
        jId11 = new javax.swing.JLabel();
        txtJawaban = new javax.swing.JTextField();
        txtCustomQuestion = new javax.swing.JTextField();
        jId12 = new javax.swing.JLabel();
        jId2 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        cbShowPassword = new javax.swing.JCheckBox();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlFilm1.setBackground(new java.awt.Color(255, 255, 255));
        jlFilm1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlFilm1.setForeground(new java.awt.Color(255, 204, 102));
        jlFilm1.setText("SIGN UP");
        jPanel1.add(jlFilm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, 40));

        jId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jId.setForeground(new java.awt.Color(255, 255, 255));
        jId.setText("Choose Type Questions :");
        jPanel1.add(jId, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, -1));
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 420, 40));
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 420, 40));

        btnBuat.setBackground(new java.awt.Color(51, 153, 0));
        btnBuat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBuat.setForeground(new java.awt.Color(255, 255, 255));
        btnBuat.setText("CREATE");
        btnBuat.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 255, 0)));
        btnBuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuatActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 770, 320, 40));

        btnBack.setBackground(new java.awt.Color(153, 0, 51));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 0)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 30));

        jId3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jId3.setForeground(new java.awt.Color(255, 255, 255));
        jId3.setText("Username :");
        jPanel1.add(jId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        cbQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQuestionActionPerformed(evt);
            }
        });
        jPanel1.add(cbQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 320, 40));

        jId6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jId6.setForeground(new java.awt.Color(255, 255, 255));
        jId6.setText(":");
        jPanel1.add(jId6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 700, 20, -1));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 740, -1));

        jId1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jId1.setForeground(new java.awt.Color(255, 255, 255));
        jId1.setText("Confirm Password :");
        jPanel1.add(jId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jId7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jId7.setForeground(new java.awt.Color(255, 255, 255));
        jId7.setText("Your Answer");
        jPanel1.add(jId7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 700, 120, -1));

        jId8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jId8.setForeground(new java.awt.Color(255, 255, 255));
        jId8.setText(":");
        jPanel1.add(jId8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, 20, -1));

        jId10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jId10.setForeground(new java.awt.Color(255, 255, 255));
        jId10.setText("Choose From List ");
        jPanel1.add(jId10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 120, -1));

        jId11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jId11.setForeground(new java.awt.Color(255, 255, 255));
        jId11.setText("Custom Question");
        jPanel1.add(jId11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, 120, -1));
        jPanel1.add(txtJawaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 690, 320, 40));
        jPanel1.add(txtCustomQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, 320, 40));

        jId12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jId12.setForeground(new java.awt.Color(255, 255, 255));
        jId12.setText(":");
        jPanel1.add(jId12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 20, -1));

        jId2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jId2.setForeground(new java.awt.Color(255, 255, 255));
        jId2.setText("Password :");
        jPanel1.add(jId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        txtConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 420, 40));

        cbShowPassword.setBackground(new java.awt.Color(51, 0, 102));
        cbShowPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        cbShowPassword.setText("Show password");
        cbShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(cbShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new LoginFrame().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuatActionPerformed
    String user = txtUser.getText().trim();
    String pw   = new String(txtPass.getPassword());
    String cpw  = new String(txtConfirmPassword.getPassword());
    String jawaban = txtJawaban.getText().trim();
    String customQ = txtCustomQuestion.getText().trim();
    int selectedIndex = cbQuestion.getSelectedIndex();

    // Validasi field wajib
    if (user.isEmpty() || pw.isEmpty() || cpw.isEmpty() || jawaban.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
        return;
    }

    // Cek password sama
    if (!pw.equals(cpw)) {
        JOptionPane.showMessageDialog(this, 
            "Password dan Konfirmasi Password tidak sama!");
        return;
    }

    // Validasi logika pertanyaan
    Integer questionId;
    boolean pilihList = selectedIndex != -1;
    boolean buatCustom = !customQ.isEmpty();

    if (!pilihList && !buatCustom) {
        JOptionPane.showMessageDialog(this,
            "Pilih pertanyaan dari daftar atau isi pertanyaan custom!");
        return;
    }

    if (pilihList && buatCustom) {
        JOptionPane.showMessageDialog(this,
            "Pilih salah satu: daftar ATAU custom question!");
        return;
    }

    if (pilihList) {
        questionId = selectedIndex + 1;
        customQ = null;
    } else {
        questionId = 0;
    }

    var em = JPAUtil.getEntityManager();
    em.getTransaction().begin();

    // Cek username sudah ada atau tidak
    Akun cek = em.find(Akun.class, user);
    if (cek != null) {
        JOptionPane.showMessageDialog(this,
            "Username sudah dipakai! Gunakan username lain.");
        em.getTransaction().rollback();
        em.close();
        return;
    }

    // Insert akun baru
    Akun a = new Akun();
    a.setUsername(user);
    a.setPassword(pw); // *Next: kita ganti jadi hashed password 🔐*
    a.setQuestionId(questionId);
    a.setSecurityAnswer(jawaban);
    a.setCustomQuestion(customQ);

    em.persist(a);
    em.getTransaction().commit();
    em.close();

    JOptionPane.showMessageDialog(this, "Berhasil Daftar!");
    new LoginFrame().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnBuatActionPerformed

    private void cbShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbShowPasswordActionPerformed

    private void txtConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPasswordActionPerformed

    private void cbQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbQuestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBuat;
    private javax.swing.JComboBox<String> cbQuestion;
    private javax.swing.JCheckBox cbShowPassword;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jId;
    private javax.swing.JLabel jId1;
    private javax.swing.JLabel jId10;
    private javax.swing.JLabel jId11;
    private javax.swing.JLabel jId12;
    private javax.swing.JLabel jId2;
    private javax.swing.JLabel jId3;
    private javax.swing.JLabel jId6;
    private javax.swing.JLabel jId7;
    private javax.swing.JLabel jId8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlFilm1;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtCustomQuestion;
    private javax.swing.JTextField txtJawaban;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
